/* DO NOT EDIT THIS FILE - it is machine generated */

import sun.misc.Unsafe;

public class CoordsXY extends Constants {
    private static final int xOffset = 0;
    private static final int xSize = doubleSize;

    public static double x (int addr) {
        return unsafe.getDouble(addr + xOffset);
    }

    private static final int yOffset = xOffset + xSize;
    private static final int ySize = doubleSize;

    public static double y (int addr) {
        return unsafe.getDouble(addr + yOffset);
    }


    static final int size = yOffset + ySize;
}

