/* DO NOT EDIT THIS FILE - it is machine generated */

import sun.misc.Unsafe;

public class FactoryClass extends Constants {
    private static final int radiusOffset = 0;
    private static final int radiusSize = doubleSize;

    public static double radius (int addr) {
        return unsafe.getDouble(addr + radiusOffset);
    }

    private static final int timeToCaptureOffset = radiusOffset + radiusSize;
    private static final int timeToCaptureSize = intSize;

    public static int timeToCapture (int addr) {
        return unsafe.getInt(addr + timeToCaptureOffset);
    }

    private static final int maxCapturingRobotsOffset = timeToCaptureOffset + timeToCaptureSize;
    private static final int maxCapturingRobotsSize = intSize;

    public static int maxCapturingRobots (int addr) {
        return unsafe.getInt(addr + maxCapturingRobotsOffset);
    }

    private static final int scoreOffset = maxCapturingRobotsOffset + maxCapturingRobotsSize;
    private static final int scoreSize = intSize;

    public static int score (int addr) {
        return unsafe.getInt(addr + scoreOffset);
    }


    static final int size = scoreOffset + scoreSize;
}

