/* DO NOT EDIT THIS FILE - it is machine generated */

import sun.misc.Unsafe;

public class Projectile extends Unit {
    private static final int velocityOffset = Unit.size;
    private static final int velocitySize = CoordsXY.size;

    public static int velocity (int addr) {
        return addr + velocityOffset;
    }

    private static final int homingTargetIdOffset = velocityOffset + velocitySize;
    private static final int homingTargetIdSize = intSize;

    public static int homingTargetId (int addr) {
        return unsafe.getInt(addr + homingTargetIdOffset);
    }

    private static final int lifeTimeRemainingOffset = homingTargetIdOffset + homingTargetIdSize;
    private static final int lifeTimeRemainingSize = doubleSize;

    public static double lifeTimeRemaining (int addr) {
        return unsafe.getDouble(addr + lifeTimeRemainingOffset);
    }


    static final int size = lifeTimeRemainingOffset + lifeTimeRemainingSize;
}

