/* DO NOT EDIT THIS FILE - it is machine generated */

import sun.misc.Unsafe;

public class RobotClass extends Constants {
    private static final int radiusOffset = 0;
    private static final int radiusSize = doubleSize;

    public static double radius (int addr) {
        return unsafe.getDouble(addr + radiusOffset);
    }

    private static final int visibilityRadiusOffset = radiusOffset + radiusSize;
    private static final int visibilityRadiusSize = doubleSize;

    public static double visibilityRadius (int addr) {
        return unsafe.getDouble(addr + visibilityRadiusOffset);
    }

    private static final int maxHealthOffset = visibilityRadiusOffset + visibilityRadiusSize;
    private static final int maxHealthSize = intSize;

    public static int maxHealth (int addr) {
        return unsafe.getInt(addr + maxHealthOffset);
    }

    private static final int maxSpeedOffset = maxHealthOffset + maxHealthSize;
    private static final int maxSpeedSize = doubleSize;

    public static double maxSpeed (int addr) {
        return unsafe.getDouble(addr + maxSpeedOffset);
    }

    private static final int projectileClassIdxOffset = maxSpeedOffset + maxSpeedSize;
    private static final int projectileClassIdxSize = intSize;

    public static int projectileClassIdx (int addr) {
        return unsafe.getInt(addr + projectileClassIdxOffset);
    }

    private static final int shootTimeCooldownOffset = projectileClassIdxOffset + projectileClassIdxSize;
    private static final int shootTimeCooldownSize = intSize;

    public static int shootTimeCooldown (int addr) {
        return unsafe.getInt(addr + shootTimeCooldownOffset);
    }

    private static final int totalAmmoOffset = shootTimeCooldownOffset + shootTimeCooldownSize;
    private static final int totalAmmoSize = intSize;

    public static int totalAmmo (int addr) {
        return unsafe.getInt(addr + totalAmmoOffset);
    }

    private static final int timeToBuildOffset = totalAmmoOffset + totalAmmoSize;
    private static final int timeToBuildSize = intSize;

    public static int timeToBuild (int addr) {
        return unsafe.getInt(addr + timeToBuildOffset);
    }

    private static final int scoreOffset = timeToBuildOffset + timeToBuildSize;
    private static final int scoreSize = intSize;

    public static int score (int addr) {
        return unsafe.getInt(addr + scoreOffset);
    }


    static final int size = scoreOffset + scoreSize;
}

