/* DO NOT EDIT THIS FILE - it is machine generated */

import sun.misc.Unsafe;

public class Unit extends Constants {
    private static final int idOffset = 0;
    private static final int idSize = intSize;

    public static int id (int addr) {
        return unsafe.getInt(addr + idOffset);
    }

    private static final int ownerOffset = idOffset + idSize;
    private static final int ownerSize = shortSize;

    public static short owner (int addr) {
        return unsafe.getShort(addr + ownerOffset);
    }

    private static final int typeOffset = ownerOffset + ownerSize;
    private static final int typeSize = shortSize;

    public static short type (int addr) {
        return unsafe.getShort(addr + typeOffset);
    }

    private static final int positionOffset = typeOffset + typeSize;
    private static final int positionSize = CoordsXY.size;

    public static int position (int addr) {
        return addr + positionOffset;
    }

    private static final int radiusOffset = positionOffset + positionSize;
    private static final int radiusSize = doubleSize;

    public static double radius (int addr) {
        return unsafe.getDouble(addr + radiusOffset);
    }

    private static final int classIdxOffset = radiusOffset + radiusSize;
    private static final int classIdxSize = intSize;

    public static int classIdx (int addr) {
        return unsafe.getInt(addr + classIdxOffset);
    }


    static final int size = classIdxOffset + classIdxSize;
}

